name: relife
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #Fontes da google
  google_fonts: ^4.0.4

  http: ^0.13.3
  crypto: ^3.0.3
  shared_preferences: ^2.1.1
  jwt_decoder: ^2.0.1
  image_picker: ^0.8.7+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #Deixar a pasta aberta, porque como é dinâmico tem que haver sempre acesso
  assets:
    - assets/images/users_profiles/
